### ISSUE TITLE
toS from Text to ByteString adds ""

### ISSUE THREAD

**Issue by joe9** [sdiehl/protolude#29] opened 2016-11-06 14:13 UTC
Hello,

Thanks for sharing Protolude.

Using toS to convert from Text to ByteString outputs this: "\"sample text here\""

whereas, using Data.String.Conversions.cs outputs this: \"sample text here\"

Is it a better idea to just export Data.String.Conversions instead instead of exporting toS?

Thanks

**Comment by sdiehl** [comment] 2016-11-06 18:59
If you'd like to inline the logic from that library inside of `Conv.hs`, I'm happy to merge. But adding another dependency isn't on the table, at least for a alt Prelude.

**Comment by cocreature** [comment] 2017-05-29 20:08
I’ve just taken a look at this but I’m unable to reproduce this, e.g., in GHCi I got
```
> toS ("sample text here" :: Text) :: ByteString
"sample text here"
```
which is exactly what I would expect here. @joe9 How exactly did you trigger this bug?

**Comment by sdiehl** [comment] 2017-05-30 09:19
Yeah,  I'm not able to reproduce this either.

**Comment by sdiehl** [comment] 2017-05-31 09:14
I think the confusion was just around the show instance inside GHCi printing double quotes. Just going to close this until we have confirmation on failure.

**Closed as completed by sdiehl** 2017-05-31 09:14 UTC
